version: "3.1"

services:
  queue_broker:
    image: rabbitmq:3.9-management
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

# add environment variables for rest-service and refactor accordingly
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"